.

diff --git a/roles/hotspot/files/autohotspotN b/roles/hotspot/files/autohotspotN
--- a/roles/hotspot/files/autohotspotN
+++ b/roles/hotspot/files/autohotspotN
@@ -1,8 +1,8 @@
 #!/bin/bash
 #version 0.95-4-N/HS-I
 
-#You may share this script on the condition a reference to RaspberryConnect.com 
-#must be included in copies or derivatives of this script. 
+#You may share this script on the condition a reference to RaspberryConnect.com
+#must be included in copies or derivatives of this script.
 
 #Network Wifi & Hotspot with Internet
 #A script to switch between a wifi network and an Internet routed Hotspot
@@ -13,7 +13,7 @@
 
 wifidev="wlan0" #device name to use. Default is wlan0.
 ethdev="eth0" #Ethernet port to use with IP tables
-#use the command: iw dev ,to see wifi interface name 
+#use the command: iw dev ,to see wifi interface name
 
 IFSdef=$IFS
 cnt=0
@@ -29,8 +29,8 @@ IFS=$IFSdef #reset back to defaults
 # separated by a space, eg ('mySSID1' 'mySSID2')
 #ssids=('mySSID1' 'mySSID2' 'mySSID3')
 
-#Enter the Routers Mac Addresses for hidden SSIDs, seperated by spaces ie 
-#( '11:22:33:44:55:66' 'aa:bb:cc:dd:ee:ff' ) 
+#Enter the Routers Mac Addresses for hidden SSIDs, seperated by spaces ie
+#( '11:22:33:44:55:66' 'aa:bb:cc:dd:ee:ff' )
 mac=()
 
 ssidsmac=("${ssids[@]}" "${mac[@]}") #combines ssid and MAC for checking
@@ -66,14 +66,14 @@ KillHotspot()
 
 ChkWifiUp()
 {
-	echo "Checking WiFi connection ok"
+        echo "Checking WiFi connection ok"
         sleep 20 #give time for connection to be completed to router
-	if ! wpa_cli -i "$wifidev" status | grep 'ip_address' >/dev/null 2>&1
+        if ! wpa_cli -i "$wifidev" status | grep 'ip_address' >/dev/null 2>&1
         then #Failed to connect to wifi (check your wifi settings, password etc)
-	       echo 'Wifi failed to connect, falling back to Hotspot.'
+               echo 'Wifi failed to connect, falling back to Hotspot.'
                wpa_cli terminate "$wifidev" >/dev/null 2>&1
-	       createAdHocNetwork
-	fi
+               createAdHocNetwork
+        fi
 }
 
 
@@ -84,44 +84,44 @@ ssidChk=('NoSSid')
 i=0; j=0
 until [ $i -eq 1 ] #wait for wifi if busy, usb wifi is slower.
 do
-        ssidreply=$((iw dev "$wifidev" scan ap-force | egrep "^BSS|SSID:") 2>&1) >/dev/null 2>&1 
+        ssidreply=$((iw dev "$wifidev" scan ap-force | egrep "^BSS|SSID:") 2>&1) >/dev/null 2>&1
         echo "SSid's in range: " $ssidreply
         echo "Device Available Check try " $j
         if (($j >= 10)); then #if busy 10 times goto hotspot
                  echo "Device busy or unavailable 10 times, going to Hotspot"
                  ssidreply=""
                  i=1
-	elif echo "$ssidreply" | grep "No such device (-19)" >/dev/null 2>&1; then
+        elif echo "$ssidreply" | grep "No such device (-19)" >/dev/null 2>&1; then
                 echo "No Device Reported, try " $j
-		NoDevice
+                NoDevice
         elif echo "$ssidreply" | grep "Network is down (-100)" >/dev/null 2>&1 ; then
                 echo "Network Not available, trying again" $j
                 j=$((j + 1))
                 sleep 2
-	elif echo "$ssidreplay" | grep "Read-only file system (-30)" >/dev/null 2>&1 ; then
-		echo "Temporary Read only file system, trying again"
-		j=$((j + 1))
-		sleep 2
-	elif ! echo "$ssidreply" | grep "resource busy (-16)"  >/dev/null 2>&1 ; then
+        elif echo "$ssidreplay" | grep "Read-only file system (-30)" >/dev/null 2>&1 ; then
+                echo "Temporary Read only file system, trying again"
+                j=$((j + 1))
+                sleep 2
+        elif ! echo "$ssidreply" | grep "resource busy (-16)"  >/dev/null 2>&1 ; then
                echo "Device Available, checking SSid Results"
-		i=1
-	else #see if device not busy in 2 seconds
+                i=1
+        else #see if device not busy in 2 seconds
                 echo "Device unavailable checking again, try " $j
-		j=$((j + 1))
-		sleep 2
-	fi
+                j=$((j + 1))
+                sleep 2
+        fi
 done
 
 for ssid in "${ssidsmac[@]}"
 do
      if (echo "$ssidreply" | grep "$ssid") >/dev/null 2>&1
      then
-	      #Valid SSid found, passing to script
+              #Valid SSid found, passing to script
               echo "Valid SSID Detected, assesing Wifi status"
               ssidChk=$ssid
               return 0
       else
-	      #No Network found, NoSSid issued"
+              #No Network found, NoSSid issued"
               echo "No SSid found, assessing WiFi status"
               ssidChk='NoSSid'
      fi
@@ -130,17 +130,17 @@ done
 
 NoDevice()
 {
-	#if no wifi device,ie usb wifi removed, activate wifi so when it is
-	#reconnected wifi to a router will be available
-	echo "No wifi device connected"
-	wpa_supplicant -B -i "$wifidev" -c /etc/wpa_supplicant/wpa_supplicant.conf >/dev/null 2>&1
-	exit 1
+        #if no wifi device,ie usb wifi removed, activate wifi so when it is
+        #reconnected wifi to a router will be available
+        echo "No wifi device connected"
+        wpa_supplicant -B -i "$wifidev" -c /etc/wpa_supplicant/wpa_supplicant.conf >/dev/null 2>&1
+        exit 1
 }
 
 FindSSID
 
 #Create Hotspot or connect to valid wifi networks
-if [ "$ssidChk" != "NoSSid" ] 
+if [ "$ssidChk" != "NoSSid" ]
 then
        echo 0 > /proc/sys/net/ipv4/ip_forward #deactivate ip forwarding
        if systemctl status hostapd | grep "(running)" >/dev/null 2>&1
